### ISSUE TITLE
npm instal faills

### ISSUE THREAD

**Issue by YorkShen** [baranov1ch/connect-sdch#3]
npm install fails due to the following problem.

> ../src/third-party/open-vcdiff/src/vcdecoder.cc:563:3: error: no type named 'unique_ptr' in namespace 'std'
>   UNIQUE_PTR<VCDiffAddressCache> addr_cache_;
>   ^~~~~~~~~~
> ../src/third-party/open-vcdiff/src/unique_ptr.h:27:25: note: expanded from macro 'UNIQUE_PTR'
> # define UNIQUE_PTR std::unique_ptr
> 
> ```
>                ~~~~~^
> ```
> 
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:563:13: error: expected member name or ';' after declaration specifiers
>   UNIQUE_PTR<VCDiffAddressCache> addr_cache_;
> 
> ``` ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:566:3: error: no type named 'unique_ptr' in namespace 'std'
>   UNIQUE_PTR<VCDiffCodeTableData> custom_code_table_;
>   ^~~~~~~~~~
> ../src/third-party/open-vcdiff/src/unique_ptr.h:27:25: note: expanded from macro 'UNIQUE_PTR'
> #define UNIQUE_PTR std::unique_ptr
>                    ~~~~~^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:566:13: error: expected member name or ';' after declaration specifiers
>   UNIQUE_PTR<VCDiffCodeTableData> custom_code_table_;
>   ~~~~~~~~~~^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:575:3: error: no type named 'unique_ptr' in namespace 'std'
>   UNIQUE_PTR<VCDiffStreamingDecoderImpl> custom_code_table_decoder_;
>   ^~~~~~~~~~
> ../src/third-party/open-vcdiff/src/unique_ptr.h:27:25: note: expanded from macro 'UNIQUE_PTR'
> #define UNIQUE_PTR std::unique_ptr
>                    ~~~~~^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:575:13: error: expected member name or ';' after declaration specifiers
>   UNIQUE_PTR<VCDiffStreamingDecoderImpl> custom_code_table_decoder_;
>   ~~~~~~~~~~^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:450:16: error: use of undeclared identifier 'custom_code_table_decoder_'; did you mean 'custom_code_table_string_'?
>     } else if (custom_code_table_decoder_.get()) {
>                ^~~~~~~~~~~~~~~~~~~~~~~~~~
>                custom_code_table_string_
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:569:10: note: 'custom_code_table_string_' declared here
>   string custom_code_table_string_;
>          ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:450:43: error: no member named 'get' in 'std::basic_string<char>'
>     } else if (custom_code_table_decoder_.get()) {
>                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:45: error: use of undeclared identifier 'addr_cache_'; did you mean 'addr_cache'?
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                                             ^~~~~~~~~~~
>                                             addr_cache
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:23: note: 'addr_cache' declared here
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                       ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:45: error: reference to non-static member function must be called; did you mean to call it with no arguments?
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                                             ^~~~~~~~~~~
>                                                        ()
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:56: error: member reference type 'open_vcdiff::VCDiffAddressCache *' is a pointer; maybe you meant to use '->'?
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                                             ~~~~~~~~~~~^
>                                                        ->
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:57: error: no member named 'get' in 'open_vcdiff::VCDiffAddressCache'
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                                             ~~~~~~~~~~~ ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:500:41: error: use of undeclared identifier 'addr_cache_'; did you mean 'addr_cache'?
>   bool FoundFileHeader() const { return addr_cache_.get() != NULL; }
>                                         ^~~~~~~~~~~
>                                         addr_cache
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:23: note: 'addr_cache' declared here
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                       ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:500:41: error: reference to non-static member function must be called
>   bool FoundFileHeader() const { return addr_cache_.get() != NULL; }
>                                         ^~~~~~~~~~~
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:643:3: error: use of undeclared identifier 'addr_cache_'; did you mean 'addr_cache'?
>   addr_cache_.reset();
>   ^~~~~~~~~~~
>   addr_cache
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:474:23: note: 'addr_cache' declared here
>   VCDiffAddressCache* addr_cache() { return addr_cache_.get(); }
>                       ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:643:3: error: reference to non-static member function must be called; did you mean to call it with no arguments?
>   addr_cache_.reset();
>   ^~~~~~~~~~~
>              ()
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:643:14: error: member reference type 'open_vcdiff::VCDiffAddressCache *' is a pointer; maybe you meant to use '->'?
>   addr_cache_.reset();
>   ~~~~~~~~~~~^
>              ->
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:643:15: error: no member named 'reset' in 'open_vcdiff::VCDiffAddressCache'
>   addr_cache_.reset();
>   ~~~~~~~~~~~ ^
> ../src/third-party/open-vcdiff/src/vcdecoder.cc:644:3: error: use of undeclared identifier 'custom_code_table_'
>   custom_code_table_.reset();
>   ^
> ```

I was using OS X Yosemite for building this. I am sure about that I have C++ 11 support complier and I can compile the [vcdiff](https://github.com/google/open-vcdiff) correctly.

**Comment by baranov1ch** [comment]
Hi, yep, there might be an issue there, although I am not able to repro it on my Yosemite 10.10.3.
The problem is that open-vcdiff here is not compiled with c++11 flag, only the bindings itself. Trying to address it.

**Comment by YorkShen** [comment]
Yeah, I thought it would be about c++ 11. But I checked binding.gyp, which contains c++11 flags. Also, I can build the "open-vcdiff" with "./configure && make" in the corresponding directory(https://github.com/baranov1ch/node-vcdiff/tree/master/src/third-party/open-vcdiff). Can you give me any advice

**Comment by baranov1ch** [comment]
It's built using node-gyp (https://github.com/baranov1ch/node-vcdiff/blob/master/src/third-party/open-vcdiff.gypi), original cmake is not used. You can try copying enabling C++11 from bindings gyp (https://github.com/baranov1ch/node-vcdiff/blob/master/binding.gyp#L22)

**Comment by baranov1ch** [comment]
I'll try to to reproduce or at least enable C++11 everywhere this week.

**Comment by YorkShen** [comment]
I already copied the following to the open-vcdiff.gypi.

> ```
>     ['OS=="mac"', {
>       'xcode_settings': {
>         'OTHER_CPLUSPLUSFLAGS': ['-std=c++11', '-stdlib=libc++'],
>         'OTHER_LDFLAGS': ['-stdlib=libc++'],
>         'MACOSX_DEPLOYMENT_TARGET': '10.7',
>       },
>     }]
> ```

The Compiling is procedure is fine, but there is a new issue in linking procedure.

>   LIBTOOL-STATIC Release/open-vcdiff.a
> error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `t' in: -stdlib=libc++
> Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
> Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
> make: **\* [Release/open-vcdiff.a] Error 1

**Comment by baranov1ch** [comment]
yep, I see this too. I'll try to fix it when I'll get some free time

**Comment by baranov1ch** [comment]
I've pushed fix here (https://github.com/baranov1ch/node-vcdiff/tree/fix-mevericks) Plz let me know if it works for you. (in a nutshell its just skipping `'OTHER_LDFLAGS': ['-stdlib=libc++'],` from open-vcdiff.gypi mac section

**Comment by YorkShen** [comment]
This still not works with following log

>   LIBTOOL-STATIC Release/open-vcdiff.a
>   CXX(target) Release/obj.target/vcdiff/src/vcd_decoder.o
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:20:29: error: expected class name
> class VcdCtx : public node::ObjectWrap {
>                             ^
> ../src/vcdiff.h:51:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
>   static v8::Handlev8::Value New(const v8::Arguments& args);
>                                          ^~~~~~~~~~~~~
>                                          v8::internal::Arguments
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
> class Arguments;
>       ^
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:52:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
>   static v8::Handlev8::Value WriteAsync(const v8::Arguments& args);
>                                                 ^~~~~~~~~~~~~
>                                                 v8::internal::Arguments
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
> class Arguments;
>       ^
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:53:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
>   static v8::Handlev8::Value WriteSync(const v8::Arguments& args);
>                                                ^~~~~~~~~~~~~
>                                                v8::internal::Arguments
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
> class Arguments;
>       ^
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:54:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
>   static v8::Handlev8::Value Close(const v8::Arguments& args);
>                                            ^~~~~~~~~~~~~
>                                            v8::internal::Arguments
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
> class Arguments;
>       ^
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:72:13: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
>       const v8::Arguments& args, bool async);
>             ^~~~~~~~~~~~~
>             v8::internal::Arguments
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
> class Arguments;
>       ^
> In file included from ../src/vcd_decoder.cc:7:
> In file included from ../src/vcd_decoder.h:14:
> ../src/vcdiff.h:85:27: error: unknown type name 'uv_work_t'
>   static void ProcessShim(uv_work_t\* work_req);
>                           ^
> ../src/vcdiff.h:86:25: error: unknown type name 'uv_work_t'
>   static void AfterShim(uv_work_t\* work_req, int status);
>                         ^
> ../src/vcdiff.h:92:3: error: unknown type name 'uv_work_t'
>   uv_work_t work_req_;
>   ^
> ../src/vcd_decoder.cc:17:54: error: 'New' is a private member of 'v8::PersistentBasev8::Object'
>       dictionary_handle_(v8::Persistentv8::Object::New(dictionary_handle)),
>                                                      ^
> /Users/sy/.node-gyp/iojs-3.2.0/include/node/v8.h:636:23: note: declared private here
>   V8_INLINE static T\* New(Isolate\* isolate, T\* that);
>                       ^
> ../src/vcd_decoder.cc:17:26: error: too few arguments to function call, expected 2, have 1; did you mean 'VcdCtx::New'?
>       dictionary_handle_(v8::Persistentv8::Object::New(dictionary_handle)),
>                          ^~
>                          VcdCtx::New
> ../src/vcdiff.h:51:32: note: 'VcdCtx::New' declared here
>   static v8::Handlev8::Value New(const v8::Arguments& args);
>                                ^
> 11 errors generated.

**Comment by baranov1ch** [comment]
which nodejs version do you use? only 0.10 is supported for now

**Comment by YorkShen** [comment]
I use iojs. It went well when I switch to node 0.10. Thank you very much.
